platform :ios, '14.0'
use_frameworks!

def pods
 pod 'Alamofire'
 pod 'SwiftLint'
 pod 'SnapKit'
 pod 'SwiftyJSON'
 pod 'Lokalise'
 pod 'SVProgressHUD'
 pod 'ReachabilitySwift'
 pod 'KeychainAccess'
 pod 'ESTabBarController-swift'
 pod 'FlagKit'
 pod 'Charts', :git => 'https://github.com/AndreyKoshkinBrander/Charts.git', :branch => 'bar-chart-bottom-border'
end

target 'ITHealth' do
  pods
end
